# Use the official Node.js image as the base image
FROM node:lts

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json files
COPY ./react-app/package*.json ./

# Install dependencies
RUN npm install

# Copy application files
COPY ./react-app /app

# Build the app
RUN npm run build

# Expose port 3000 for development
EXPOSE 3000

# Start the app
CMD ["npm", "start"]