# Dockerfile.local for React (Node.js) development

FROM node:lts

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json files
COPY ./src/react-app/package*.json ./

# Install dependencies
RUN npm install

# Copy application files
COPY ./src/react-app /app

# Expose port 3000 for development
EXPOSE 3000

# Start the React development server
CMD ["npm", "start"]